# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RDF-Scutter
version:      0.01
version_from: lib/RDF/Scutter.pm
installdirs:  site
requires:
    LWP::RobotUA:                  0
